services:
  - type: web
    name: django-canape
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn src.main.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: main.settings
      - key: PYTHON_VERSION
        value: 3.10
